version: "3.8"
services:
  neovim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neovim_ide
    hostname: neovim
    stdin_open: true
    tty: true
    volumes:
      - ./nvim/:/root/dotfiles/nvim/
